# Generated by Django 2.2 on 2020-03-09 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clasificar',
            fields=[
                ('fileid', models.AutoField(primary_key=True, serialize=False)),
                ('fileName', models.CharField(max_length=20)),
                ('fileUpload', models.FileField(upload_to='files/')),
                ('dateC', models.DateTimeField(auto_now_add=True, verbose_name='Date Published')),
                ('dateU', models.DateTimeField(auto_now=True, null=True, verbose_name='Date Update')),
            ],
            options={
                'verbose_name_plural': 'Gestor de Archivos',
            },
        ),
    ]
